---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and nginx packages
    package:
      name: 
        - "{{ nginx_package }}"
        - "{{ apache2_package }}"
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
