---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 package
    apt:
      name: apache2 
      state: absent

  - name: remove nginx package
    apt:
      name: nginx
      state: absent
