---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      #upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install nginx package
    tags: nginx,ubuntu
    apt:
      name: 
        - nginx
      state: latest
    when: ansible_distribution in ["Ubuntu"]

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (Ubuntu)
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu" 
