- name: install apache package
  tags: apache,ubuntu
  apt:
    name:
      - apache2
    state: latest
  when: ansible_distribution in ["Ubuntu"]

- name: copy default html file for site
  tags: apache,ubuntu
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
